### ISSUE TITLE
Request: Support for eslint?

### ISSUE THREAD

**Issue by kirkstrobeck** [jonlabelle/SublimeJsPrettier#35]
I would like super+b to run prettier, then eslint --fix so it keeps my formatting.

**Comment by jonlabelle** [comment]
You can run a post command, but this plugin only supports prettier.

**Comment by kentcdodds** [comment]
Wondering whether you'd be interested in resurrecting this. A lot of people don't adopt prettier due to sub-optimal integration with eslint and prettier-eslint helps to solve this pain point. You can see the arguments for adding this as well as how it was added to the VSCode plugin [here](https://github.com/esbenp/prettier-vscode/issues/70). ESLint integration is also supported by the official Atom plugin as well.

Thanks for your work and consideration here :)

**Comment by tunnckoCore** [comment]
@kentcdodds absolutely agree!

Btw, @kentcdodds, most easier thing for better integrations between such tools would be `prettier-eslint` to mimic the original `prettier` CLI arguments. It's absolutely needless to have `--prettier.foo` signature there. I don't see the problem to just pass rest flags/options directly to prettier - there's no collisions between them and these that are added by `prettier-eslint`.
So if `prettier-eslint` is absolutely the same, here we can just add option to use `prettier-eslint` string instead of `prettier`.

**Comment by kentcdodds** [comment]
Good point. I think that I'd be willing to look at a pull request for that 👍

**Comment by tunnckoCore** [comment]
@kentcdodds great! I'll look to send when get a bit time. :pray:

**Comment by tunnckoCore** [comment]
@jonlabelle, it's not more easier to integrate `prettier-eslint`, so you can just try to find it first, and fallback to prettier's cli.

**Comment by jonlabelle** [comment]
@tunnckoCore I will definitely have a look.

**Comment by jonlabelle** [comment]
I'm curious to see if this enhancement is now resolved by specifying the path to `prettier-eslint` in the [`prettier_cli_path`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L40) setting, and then adding any additional [prettier-eslint-cli](https://github.com/prettier/prettier-eslint-cli#cli-options) options to the [`additional_cli_args`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L109) setting (available since [v1.8](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/CHANGELOG.md#190)).

Any takers want to give it a shot...? I haven't had the opportunity yet to try it out myself.

**Comment by tunnckoCore** [comment]
Hmm.. Actually if i remember correctly, while looking over the code, that was the reason why I made the PR to `prettier-eslint-cli` first. So probably it may work, i believe.

While it may be possible currently, it still won't be good feel to pass path to cli manually. Probably just passing the CLI _name_ instead of the _cli path_, would be better.

**Comment by jonlabelle** [comment]
Though not an extensive test by any means... I did install [prettier-eslint](https://github.com/prettier/prettier-eslint) globally, then update my User overridden [JsPrettier.sublime-settings](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings) file to read `"prettier_cli_path": "/usr/local/bin/prettier-eslint"`.

Formatting via prettier worked perfectly, but I don't have eslint configured (in any way)... so I wasn't able to validate its supposed operations.

**Comment by kentcdodds** [comment]
Well, that's _also_ good to get verified (that things still work even if you don't have eslint configured) :)

**Comment by jonlabelle** [comment]
Just noticed that prettier-eslint-cli doesn't yet allow passing in a path to an .eslint config file ([see issue](https://github.com/prettier/prettier-eslint-cli/issues/37)). Maybe once [this enhancement](https://github.com/prettier/prettier-eslint-cli/issues/37) is introduced, we can revisit using it as a drop-in replacement.

**Comment by kentcdodds** [comment]
Hmmm. The fact is, most people don't need the ability to specify the eslint config because the correct one is identified via ESLint's usual means (searching up the file tree until one is found). It is very expected behavior...

**Comment by ljharb** [comment]
@jonlabelle any chance this could be reopened, to use eslint's default config path mechanisms? Adding the enhancement later of passing in a path to a config file shouldn't need to block this.

**Comment by badsyntax** [comment]
I've managed to get this to work as outlined here: #84 

+1 for this plugin supporting prettier-eslint.

**Comment by sharmilajesupaul** [comment]
just wanted to also note, [prettier-eslint-cli](https://github.com/prettier/prettier-eslint-cli#cli-options) added an option to pass in a custom eslint config back in August, so now we can use `--eslint-config-path` (issue: https://github.com/prettier/prettier-eslint-cli/issues/37).

**Comment by jonlabelle** [comment]
@ljharb `prettier-eslint` should already work as plug-in replacement for `prettier`.

You just need to update your [`prettier_cli_path`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L50) to the appropriate path of your `prettier-eslint` install, then you can use [`additional_cli_args`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L185) for anything specific to `prettier-eslint`.

**Comment by ljharb** [comment]
I appreciate that [that](https://github.com/jonlabelle/SublimeJsPrettier/issues/84#issuecomment-339577432) will make it work, but that means it doesn't work out of the box, which means it's harder to explain to people how to set it up :-/

**Comment by jonlabelle** [comment]
@ljharb Can you describe the rules and expected behavior of the *[out of the box](https://github.com/jonlabelle/SublimeJsPrettier/issues/35#issuecomment-339840645)* operation

Maybe provide a decision tree for determining which command to use (`prettier` or `prettier-es-lint`) without any type of specification by the user (e.g. in the [`prettier_cli_path`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L50))

**Comment by ljharb** [comment]
if `type ./node_modules/.bin/prettier-eslint`, use that, else use `./node_modules/.bin/prettier`, otherwise either do nothing (since nothing should ever be globally installed) or fall back to the global `prettier` (to maintain legacy behavior).
